/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/deliver': RouteRecordInfo<'/deliver', '/deliver', Record<never, never>, Record<never, never>>,
    '/deliverOrder': RouteRecordInfo<'/deliverOrder', '/deliverOrder', Record<never, never>, Record<never, never>>,
    '/product': RouteRecordInfo<'/product', '/product', Record<never, never>, Record<never, never>>,
    '/robot': RouteRecordInfo<'/robot', '/robot', Record<never, never>, Record<never, never>>,
    '/stockOrder': RouteRecordInfo<'/stockOrder', '/stockOrder', Record<never, never>, Record<never, never>>,
  }
}
